services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  cmarket_backend:
    build:
      context: .
    container_name: cmarket-backend
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"