services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"

  cmarket_backend:
    build:
      context: .
    container_name: cmarket-backend
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"